[build-system]
requires = ["setuptools", "torch", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "simple-knn"
dependencies = []
requires-python = ">=3.8"
authors = []
maintainers = []
description = ""
readme = "README.md"